// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5EpvGbxWvMZ4-si0jV9UArRDYOU1uyzg',
    appId: '1:331115187512:web:430b49539a5a8937b885cd',
    messagingSenderId: '331115187512',
    projectId: 'scanspend-4fab0',
    authDomain: 'scanspend-4fab0.firebaseapp.com',
    storageBucket: 'scanspend-4fab0.firebasestorage.app',
    measurementId: 'G-81H2517BTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc-Ner5VG7YmkmBM0xO1HTmKPjYboIL0U',
    appId: '1:331115187512:android:6ca1d4fbd7c41e7cb885cd',
    messagingSenderId: '331115187512',
    projectId: 'scanspend-4fab0',
    storageBucket: 'scanspend-4fab0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvJoIErcCbAmkSaok92ay_PmCvsxPWkBw',
    appId: '1:331115187512:ios:704ada1e21975f51b885cd',
    messagingSenderId: '331115187512',
    projectId: 'scanspend-4fab0',
    storageBucket: 'scanspend-4fab0.firebasestorage.app',
    iosBundleId: 'com.example.scanspend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvJoIErcCbAmkSaok92ay_PmCvsxPWkBw',
    appId: '1:331115187512:ios:704ada1e21975f51b885cd',
    messagingSenderId: '331115187512',
    projectId: 'scanspend-4fab0',
    storageBucket: 'scanspend-4fab0.firebasestorage.app',
    iosBundleId: 'com.example.scanspend',
  );
}
